# This workflow runs edgetest on lazyscribe @ 17:20 UTC Fridays.
# https://github.com/edgetest-dev/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@v1.6
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'main'
          skip-pr: 'true'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'

      - name: Update uv lock
        run: uv lock --upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: edgetest-patch
          base: main
          delete-branch: true
          title: 'upgrade(deps): update dependencies with edgetest'
          commit-message: 'upgrade(deps): update dependencies with edgetest'
          body: >
            Automated changes by [edgetest](https://github.com/edgetest-dev/run-edgetest-action) GitHub action
            and uv updating `uv.lock`.
          add-paths: |
            pyproject.toml
            uv.lock
